dependencies:
- name: contracts
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.88
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.88
- name: login
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.90
- name: login-front
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: profile
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.26
