dependencies:
- name: contracts
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.28
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.88
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.88
- name: login
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.89
- name: profile
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.24
